---
- name: Start DDOS attack simulation
  hosts: all
  gather_facts: no

  tasks:
    - name: copy ddosattack systemd timer file
      copy:
        src: ddosattack.timer
        dest: /etc/systemd/system/ddosattack.timer
            
    - name: copy systemd service file
      template:
        src: ddosattack.service.j2
        dest: /etc/systemd/system/ddosattack.service
            
    - name: systemd daemon-reload
      systemd:
        daemon_reload: yes

    - name: systemctl start ddosattack timer
      systemd:
        name: ddosattack.timer
        state: started

    - name: systemctl start ddosattack service
      systemd:
        name: ddosattack.service
        state: started
