---
- name: start attack
  hosts: all
  gather_facts: no

  tasks:
    - name: copy systemd timer file
      copy:
        src: curl.timer
        dest: /etc/systemd/system/curl.timer
            
    - name: copy systemd service file
      template:
        src: curl.service.j2
        dest: /etc/systemd/system/curl.service
            
    - name: systemd daemon-reload
      systemd:
        daemon_reload: yes

    - name: system start timer
      systemd:
        name: curl.timer
        state: started
