---
- name: Kill simulated DDOS attack
  hosts: all

  tasks:
    - name: Disable ddosattack timer
      systemd:
        name: ddosattack.timer
        state: stopped

    - name: Stop ddosattack service
      systemd:
        name: ddosattack.service
        state: stopped
