---
- name: Add web ids signature for web attack
  hosts: all

  vars:
    ids_provider: snort
    protocol: tcp
    source_port: any
    source_ip: any
    dest_port: any
    dest_ip: any

  tasks:
    - name: Add snort attack rule
      include_role:
        name: "ansible_security.ids_rule"
      vars:
        ids_rule: "{{ tower_snort_rule }}"
        # alert tcp any any -> any any  (msg:"Attempted Web Attack"; uricontent:"/web_attack_simulation"; classtype:web-application-attack; sid:99000020; priority:1; rev:1;)
        ids_rules_file: '/etc/snort/rules/local.rules'
        ids_rule_state: present
