---

# Projects
- name: Add git repository as Tower project
  awx.awx.project:
    name: "Workshop Project"
    organization: "Default"
    scm_type: git
    scm_url: "https://github.com/ansible-security/workshop-examples.git"
    validate_certs: false
  register: add_repo
  until: add_repo is not failed
  retries: 5
  delay: 10

- name: Add other git project
  awx.awx.project:
    name: "BH Github Project"
    organization: "Default"
    scm_type: git
    scm_url: "https://github.com/AQuack/workshop-examples.git"
    validate_certs: false
  register: add_repo
  until: add_repo is not failed
  retries: 5
  delay: 10


- name: Wait for update to finish
  pause:
    minutes: 1

# Add execution environment
# This could be updated in the future to remove this requirement
- name: Add execution environmnet as Controller object
  awx.awx.execution_environment:
    name: "BH EE"
    image: "quay.io/aquacken/rfshsec:latest"
    credential: "Controller Credential"
    validate_certs: false

# Job templates
- name: Job template sending firewall logs to QRadar
  awx.awx.job_template:
    name: "Send firewall logs to QRadar"
    job_type: "run"
    inventory: "Workshop Inventory"
    project: "BH Mini Project"
    playbook: "cp_log.yml"
    state: "present"
    limit: "checkpoint"
    execution_environment: "{{ workshop_type }} workshop execution environment"
    credential: "Workshop Credential"
    use_fact_cache: true
    validate_certs: false

- name: Job template sending IDPS logs to QRadar
  awx.awx.job_template:
    name: "Send IDPS logs to QRadar"
    job_type: "run"
    inventory: "Workshop Inventory"
    project: "BH Mini Project"    
    playbook: "idps_log.yml"
    state: "present"
    limit: "snort"
    credential: "Workshop Credential"
    become_enabled: true
    execution_environment: "{{ workshop_type }} workshop execution environment"
    use_fact_cache: true
    validate_certs: false

- name: Job template accepting firewall logs in QRadar
  awx.awx.job_template:
    name: "Accept firewall logs in QRadar"
    job_type: "run"
    inventory: "Workshop Inventory"
    project: "BH Mini Project"
    playbook: "qradar_cp_log.yml"
    state: "present"
    limit: "qradar"
    execution_environment: "{{ workshop_type }} workshop execution environment"
    credential: "Workshop Credential"
    use_fact_cache: true
    validate_certs: false

- name: Job template accepting IDPS logs in QRadar
  awx.awx.job_template:
    name: "Accept IDPS logs in QRadar"
    job_type: "run"
    inventory: "Workshop Inventory"
    project: "BH Mini Project"
    playbook: "qradar_snort_log.yml"
    state: "present"
    limit: "qradar"
    credential: "Workshop Credential"
    execution_environment: "{{ workshop_type }} workshop execution environment"
    use_fact_cache: true
    validate_certs: false

- name: Job template rolling back everything
  awx.awx.job_template:
    name: "Roll back all changes"
    job_type: "run"
    inventory: "Workshop Inventory"
    project: "BH Mini Project"
    playbook: "rollback.yml"
    state: "present"
    credential: "Workshop Credential"
    execution_environment: "{{ workshop_type }} workshop execution environment"
    use_fact_cache: true
    validate_certs: false

- name: Job template adding web attack IDPS rule
  awx.awx.job_template:
    name: "Add IDPS rule"
    job_type: "run"
    inventory: "Workshop Inventory"
    project: "BH Mini Project"
    playbook: "web_snort_rule.yml"
    state: "present"
    limit: "snort"
    credential: "Workshop Credential"
    become_enabled: true
    survey_enabled: true
    survey_spec: "{{ lookup('templates', 'security_survey_ids_rule.json') }}"
    execution_environment: "{{ workshop_type }} workshop execution environment"
    use_fact_cache: true
    validate_certs: false

- name: Job template adding start web attack simulation
  awx.awx.job_template:
    name: "Start web attack simulation"
    job_type: "run"
    inventory: "Workshop Inventory"
    project: "BH Mini Project"
    playbook: "start_web_attack_sim.yml"
    state: "present"
    limit: "attacker"
    credential: "Workshop Credential"
    become_enabled: true
    execution_environment: "{{ workshop_type }} workshop execution environment"
    use_fact_cache: true
    validate_certs: false

- name: Job template adding stop web attack simulation
  awx.awx.job_template:
    name: "Stop web attack simulation"
    job_type: "run"
    inventory: "Workshop Inventory"
    project: "BH Mini Project"
    playbook: "stop_web_attack_sim.yml"
    state: "present"
    limit: "attacker"
    credential: "Workshop Credential"
    become_enabled: true
    execution_environment: "{{ workshop_type }} workshop execution environment"
    use_fact_cache: true
    validate_certs: false

- name: Job template adding allow entry for attacker
  awx.awx.job_template:
    name: "Allow attacker"
    job_type: "run"
    inventory: "Workshop Inventory"
    project: "BH Mini Project"
    playbook: "allowdeny_attacker.yml"
    state: "present"
    limit: "checkpoint"
    execution_environment: "BH EE"
    credential: "Workshop Credential"
    use_fact_cache: true
    validate_certs: false
  
- name: Job template adding deny entry for attacker
  awx.awx.job_template:
    name: "Deny attacker"
    job_type: "run"
    inventory: "Workshop Inventory"
    project: "BH Mini Project"
    playbook: "allowdeny_attacker.yml"
    state: "present"
    limit: "checkpoint"
    extra_vars: "action_choice: deny"
    execution_environment: "BH EE"
    credential: "Workshop Credential"
    use_fact_cache: true
    validate_certs: false

- name: Job template adding rollback for checkpoint
  awx.awx.job_template:
    name: "Rollback Checkpoint"
    job_type: "run"
    inventory: "Workshop Inventory"
    project: "BH Mini Project"
    playbook: "rollback_cp.yml"
    state: "present"
    limit: "checkpoint"
    execution_environment: "BH EE"
    credential: "Workshop Credential"
    use_fact_cache: true
    validate_certs: false

